djangotweet2/djangotweet2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tweetapp/", include('tweetapp.urls')),
    path("", include('django.contrib.auth.urls'))
]

djangotweet2/tweetapp/urls.py
from django.urls import path
from . import views

app_name = 'tweetapp'

urlpatterns = [
    path("", views.listtweet, name='listtweet' ),  #esay.com/tweetapp/
    path("addtweet/", views.addtweet, name='addtweet' ), #esay.com/tweetapp/addtweet/
    path("addtweetbyform/", views.addtweetbyform, name='addtweetbyform' ), #esay.com/tweetapp/addtweetbyform/ 
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path("deletetweet/<int:id>", views.deletetweet, name='deletetweet')
]

djangotweet2/tweetapp/models.py
from django.db import models
from django.contrib.auth.models import User



class Tweet(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    message = models.CharField(max_length=100)


    def __str__(self):
        return f"Tweet nick: {self.username} message: {self.message}"

djangotweet2/tweetapp/forms.py
from django import forms


class AddTweetForm(forms.Form):
    nickname_input = forms.CharField(label = 'username', max_length=50)
    message_input = forms.CharField(label='Message', max_length=100)

djangotweet2/tweetapp/views.py
from django.shortcuts import render, redirect
from . import models
from django.urls import reverse, reverse_lazy
from tweetapp.forms import AddTweetForm
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView

def listtweet(request):
    all_tweets = models.Tweet.objects.all()
    tweet_dict = {"tweets":all_tweets}
    return render(request, 'tweetapp/listtweet.html', context=tweet_dict)


def addtweet(request):
    # print(request.POST)
    """
    if request.POST:
        print(request.POST["username"])
        print(request.POST["message"])
    """
    if request.POST:
        message = request.POST["message"]
        models.Tweet.objects.create(username = request.user, message = message)
        return redirect(reverse('tweetapp:listtweet'))
    else:
        return render(request, 'tweetapp/addtweet.html')


def addtweetbyform(request):
    if request.method == "POST":
        form = AddTweetForm(request.POST)
        if form.is_valid():
            nickname = form.cleaned_data['nickname_input']
            message = form.cleaned_data['message_input']
            models.Tweet.objects.create(nickname=nickname, message=message)
        
            return redirect(reverse('tweetapp:listtweet'))
        else:
            print("error in form!")
            return render(request, "tweetapp/addtweetbyform.html", context={'form':form})
    else:
        form = AddTweetForm()
        return render(request, "tweetapp/addtweetbyform.html", context={'form':form})
    

def deletetweet(request, id):
    tweet = models.Tweet.objects.get(pk=id)
    if request.user == tweet.username:
        models.Tweet.objects.filter(id=id).delete()
        return redirect("tweetapp:listtweet")
    

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

djangotweet2/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Tweet App</title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Easyso Tweet App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'tweetapp:listtweet' %}">List Tweet</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweetapp:addtweet' %}#">Add Tweet</a>
              </li>
              <!--- authendication icin bu kismi yorum satiri yaptik
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweetapp:addtweetbyform' %}#">Add Tweet by form</a>
              </li>
              -->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}#">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}#">Logout</a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweetapp:signup' %}">Sign Up</a>
              </li>  
            </ul>
          </div>
        </div>
      </nav>

    {%block content%}

    {%endblock%}

    
</body>
</html>

djangotweet2/tweetapp/templates/tweetapp/addtweet.html
{% extends "base.html" %}

{%block content%}


<form action="" method="POST">
    {% csrf_token %}
    <div class="container" style="width: 50%;">
            <!--
        <div class="mb-3">
        <label for="nickname" class="form-label">Nickname : </label>
        <input class="text" class="form-control" id="nickname" name="nickname">
     </div>
            -->
     <div class="mb-3">
        <label for="message" class="form-label" style="width: fit-content;">Message : </label>
        <input type="text" class="form-control" id="message" name="message">
     </div>
     <button type="submit" class="btn btn-primary">Send Tweet</button>
    <div>
    </form>
  

{%endblock%}

djangotweet2/tweetapp/templates/tweetapp/addtweetbyform.html
{% extends "base.html" %}

{%block content%}


<h1>AddTweetByForm page</h1>


<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <br>
    <button type="submit" class="btn btn-primary">Send Tweet</button>
  </form>


{%endblock%}

djangotweet2/tweetapp/templates/tweetapp/listtweet.html
{% extends "base.html" %}

{%block content%}



    <div class="container" style="width: 50%;">
    {% for tweet in tweets%}
        <div class="card" style="padding: 10px;">
            <div class="card-header" style="background-color: cornflowerblue;">
                <h3>{{tweet.username}}</h3>
            </div>
            <div class="card-body">
                <p class="card-text">{{tweet.message}}</p>
            </div>
            {%if tweet.username == user%}
            <a href="{% url 'tweetapp:deletetweet' id=tweet.id %}" class="btn btn-danger">Delete</a>
            {%endif%}

        </div>
    {%endfor%}

    </div>



{%endblock%}